import = [
  "~/.config/grub-darker.toml"
]

[font]
size = 13.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = false

[env]
TERM="xterm-256color"
