general.import = [
  "~/.config/nvim-dark.toml"
]

[font]
size = 14.0

[font.offset]
x = 0
y = -1

[font.normal]
family = "InputMonoCompressed"

[selection]
save_to_clipboard = false

[window]
dynamic_padding = true
