import = [
  "~/.config/vscode-light.toml"
]

[font]
size = 14.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = false

