[colors.primary]
background = "#fefefe"
foreground = "#000000"

[colors.cursor]
text = "#000000"
cursor = "#0078d7"

[colors.normal]
black = "#000000"
red = "#ff0000"
green = "#008000"
yellow = "#daa520"
blue = "#000080"
magenta = "#800080"
cyan = "#008080"
white = "#c0c0c0"

[colors.selection]
text = "#fefefe"
background = "#0078d7"
